server {
    listen 80;
    server_name localhost;

    location = / {
        return 301 /app/;
    }

    location = /app {
        return 301 /app/;
    }

    location /icons.svg {
        root /usr/share/nginx/html;
    }

    location /app/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /app/index.html;
    }

    location /api/ {
        proxy_pass http://backend:5000/;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cookie_path / /;
    }
}